name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build-image.yml
      - ./Dockerfile
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build-image.yml
      - ./Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/dgunay/dominions-5-env:${SHORT_SHA}
    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to ghcr.io
      run : docker push ghcr.io/dgunay/dominions-5-env:${SHORT_SHA}
